# Generated by Django 5.0 on 2024-04-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollows',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfollows',
            name='followers',
            field=models.ManyToManyField(blank=True, to='review.userfollows'),
        ),
    ]
