# Generated by Django 5.0 on 2024-04-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_ticket_user_ticket_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user_ticket_number',
        ),
    ]
