# Generated by Django 5.0 on 2024-04-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_remove_ticket_user_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user_ticket_number',
            field=models.IntegerField(default=1),
        ),
    ]
