# Generated by Django 5.0 on 2024-04-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_ticket_user_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, default='../static/images/no-image.jpg', null=True, upload_to=''),
        ),
    ]
