# Generated by Django 5.0 on 2024-04-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_ticket_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollows',
            old_name='followers',
            new_name='follower',
        ),
    ]
