# Generated by Django 5.0 on 2024-04-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_rename_followers_userfollows_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollows',
            name='follower',
        ),
    ]
