# Generated by Django 5.0 on 2024-04-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_remove_userfollows_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='ticket_images/'),
        ),
    ]
