# Generated by Django 5.0 on 2024-04-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_alter_ticketreview_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
